//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELMOS7AF
{
    using System;
    using System.Collections.Generic;
    
    public partial class daysRevenue
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> starting { get; set; }
        public Nullable<double> ending { get; set; }
        public string annotations { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<double> outcome { get; set; }
        public Nullable<double> incomes { get; set; }
    }
}
